### ISSUE TITLE
🐛 Bug Report: Code blocks don't render inside post

### ISSUE THREAD

**Issue by omnigenous** [redlib-org/redlib#227]
## Describe the bug

Code blocks don't render inside post but work inside comments

## Steps to reproduce the bug

1. Go to https://www.reddit.com/r/commandline/comments/1fe8uwc/want_to_share_how_i_refer_previous_command_i_use/
4. See code blocks not redering inside post but comments code block work

## Additional context / screenshot

![2024-09-14_15-11-46](https://github.com/user-attachments/assets/744d8bc2-8847-41ae-8c4f-f225529cc12f)

**Comment by freedit-dev** [comment]
Maybe we should render the markdown ourselves. I’m not sure whether we should render everything ourselves or just render the text that contains ``` blocks. What do you think? @sigaloid 

selftext_html

```html
<!-- SC_OFF --><div class="md"><p>This was a fun one that bit our open source project today...a log::error! macro in an enum that recursively printed itself.</p>

<p>Be careful out there println!ers 😂</p>

<p><a href="https://preview.redd.it/f7ikci93sx0e1.png?width=2016&amp;format=png&amp;auto=webp&amp;s=9b7ca26ae2f9f71b8b1960423caac2489c5f38ec">https://preview.redd.it/f7ikci93sx0e1.png?width=2016&amp;format=png&amp;auto=webp&amp;s=9b7ca26ae2f9f71b8b1960423caac2489c5f38ec</a></p>
</div><!-- SC_ON -->
text: This was a fun one that bit our open source project today...a log::error! macro in an enum that recursively printed itself.

Be careful out there println!ers 😂

https://preview.redd.it/f7ikci93sx0e1.png?width=2016&format=png&auto=webp&s=9b7ca26ae2f9f71b8b1960423caac2489c5f38ec

  

html: <!-- SC_OFF --><div class="md"><p>Despite the use of caching, my compile/test steps takes several minutes to execute, even if zero changes exist between runs.</p>

<p>```yaml
version: 2.1</p>

<p>commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          key: cache_cmd-v1-{{ arch }}-{{ checksum &quot;Cargo.lock&quot; }}</p>

<p>save_cache_cmd:
    steps:
      - save_cache:
          key: cache_cmd-v1-{{ arch }}-{{ checksum &quot;Cargo.lock&quot; }}
          paths:
            - &quot;~/.cargo&quot;
            - &quot;./target&quot;</p>

<p>jobs:
  # Precompile all the rust dependencies
  compile:
    executor: nix-executor
    steps:
      - restore_cache_cmd
      - run:
          name: Compile App
          command: |
            cargo zigbuild --target x86_64-unknown-linux-musl --bin server --release
      - save_cache_cmd
```</p>

<p>Critically, I see that the deps are not compiled but the binaries takes in this step like 6 min.</p>
</div><!-- SC_ON -->
```

selftext: 

````
Despite the use of caching, my compile/test steps takes several minutes to execute, even if zero changes exist between runs.


```yaml
version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          key: cache_cmd-v1-{{ arch }}-{{ checksum "Cargo.lock" }}

  save_cache_cmd:
    steps:
      - save_cache:
          key: cache_cmd-v1-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"

jobs:
  # Precompile all the rust dependencies
  compile:
    executor: nix-executor
    steps:
      - restore_cache_cmd
      - run:
          name: Compile App
          command: |
            cargo zigbuild --target x86_64-unknown-linux-musl --bin server --release
      - save_cache_cmd
```

Critically, I see that the deps are not compiled but the binaries takes in this step like 6 min.
````
