### ISSUE TITLE
💡 Feature request: allow setting of system theme for light and dark

### ISSUE THREAD

**Issue by helmut72** [redlib-org/redlib#299]
## Is your feature request related to a problem? Please describe.

I have problems reading red text on dark background. I have set redlib to use system theme to be in sync of my desktop and phone setting.

## Describe the feature you would like to be implemented

Would be cool if light and dark theme can be set for system theme.

## Describe alternatives you've considered

Don' use system theme and manually change theme regarding to my desktop or phone setting.

## Additional context / screenshot

Thank you.

**Comment by DokterKaj** [comment]
Hey, not sure I really understand what's being requested here; can you elaborate in more detail?

If it's about customising the accent colour, I recommend using [Stylus](https://github.com/openstyles/stylus) and adding something like this:
```css
:root {
    --accent: <your dark colour>;
}

@media (prefers-color-scheme: light) {
    :root {
        --accent: <your light colour>;
        color-scheme: light;
    }
}
```
